changed location id to random generated string
FullOfPit/Teamproject_Stray pull request #9
Opened 2023-01-12 12:07 UTC by chuettenrauch

2023-01-12 16:54 UTC, FullOfPit commented on backend/src/test/java/com/example/backend/controller/TripsControllerTest.java
> +                .andExpect(jsonPath("$.locations.*.id", notNullValue()));
Test läuft auch noch, wenn die id-generation im TestService auskommentiert wurde?

2023-01-12 16:54 UTC, FullOfPit requested changes
Siehe Kommentar bei TripControllerTest

2023-01-12 18:17 UTC, chuettenrauch commented on backend/src/test/java/com/example/backend/controller/TripsControllerTest.java
> +                .andExpect(jsonPath("$.locations.*.id", notNullValue()));
Fixed. 
Der JsonPath war richtig, nur der Matcher nicht. Mit dem JsonPath wird das Location Array mit IDs selected, also 
```json
[null, null]
```
Das ist logischerweise kein `null`-value - deswegen hat der das durchgelassen. 

Hab das jetzt so angepasst, dass er prüft, dass das ID array 2 Elemente hat und beide nicht null sind

2023-01-13 07:43 UTC, FullOfPit approved these changes
Sieht erstmal gut aus!

2023-01-13 08:05 UTC, merged